 # app.yaml
    runtime: python27
    api_version: 1
    threadsafe: true
    env: flex
    handlers:
    - url: /.*
      script: application.app

    #[START env]
    #env_variables:
        #CLOUD_STORAGE_BUCKET: khet-online-storage
    #[END env]