 # app.yaml
runtime: python
runtime_config:
  python_version: 3
api_version: 1
threadsafe: true
env: flex
entrypoint: python main.py

    #[START env]
    #env_variables:
        #CLOUD_STORAGE_BUCKET: khet-online-storage
    #[END env]