"""empty message

Revision ID: 55234154e085
Revises: 
Create Date: 2019-03-24 05:23:12.386879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55234154e085'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('confirmed_users', sa.String(length=1000), nullable=True),
    sa.Column('event_date', sa.String(length=20), nullable=True),
    sa.Column('event_creator', sa.String(length=128), nullable=True),
    sa.Column('fileLocation', sa.String(length=128), nullable=True),
    sa.Column('agreed', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('time', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('event')
    # ### end Alembic commands ###
